name: 'CI: Lint and Build'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies with retry
        run: |
          for i in 1 2 3; do
            echo "Attempt $i: installing dependencies..."
            yarn install --frozen-lockfile && break || sleep 20
          done

      - name: Lint JavaScript
        run: yarn lint:js:ci

      - name: Lint CSS
        run: yarn lint:css:ci

      - name: Build project
        run: yarn build
